### ISSUE TITLE
Matlab version

### ISSUE THREAD

**Issue by marialarsson** [yiwei-hu/SVBRDF-Proceduralization#2]
Which Matlab version are you using? **R2021b** appears to be the latest version compatible with Python 3.7. In debugging some other issues, I wanted to check which is the best version to use, though.

**Comment by yiwei-hu** [comment]
The code was tested with Python 3.7 + Matlab R2021b on Windows 10. If you have trouble with running the matting code, you may also try other version of VLFeat from [vlfeat.org](url).

**Comment by WinnifredJacquesT7** [comment]
Thank you for the information. I'll keep that in mind. Let me know if you have any other questions or concerns.
